name: Tests
on:
  push:
    branches: [badge]
  pull_request:
    types: [opened, closed]
    branches: [main, master, pipfile-experiment]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: kojoru/prepare-pipenv@v1
        with:
          python-version: "3.11"
      - name: Turn on editable mode install
        run: |
          pipenv install -e .
      - name: Run the tests
        run: |
          pipenv install pytest
          pipenv --venv
          pipenv run python -m pytest